# Generated by Django 5.1.7 on 2025-03-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0002_remove_employee_department_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('date', 'Date'), ('boolean', 'Booléen'), ('select', 'Sélection')], max_length=20, verbose_name='Type de champ')),
                ('model_type', models.CharField(choices=[('job', 'Emploi'), ('position', 'Poste'), ('employee', 'Employé'), ('skill', 'Compétence')], max_length=50, verbose_name='Type de modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('options', models.TextField(blank=True, help_text="Options séparées par des virgules (pour type 'select')", verbose_name='Options')),
            ],
            options={
                'verbose_name': 'Champ personnalisé',
                'verbose_name_plural': 'Champs personnalisés',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField(verbose_name='Valeur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.customfield', verbose_name='Champ personnalisé')),
            ],
            options={
                'verbose_name': 'Valeur de champ personnalisé',
                'verbose_name_plural': 'Valeurs de champs personnalisés',
                'unique_together': {('custom_field', 'content_type', 'object_id')},
            },
        ),
    ]
