# Generated by Django 5.1.7 on 2025-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='model_type',
            field=models.CharField(choices=[('job', 'Emploi'), ('position', 'Poste'), ('employee', 'Employé'), ('skill', 'Compétence'), ('job_family', 'Famille de métiers')], max_length=50, verbose_name='Type de modèle'),
        ),
    ]
